[package]
name = "wut"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
indicatif = "0.17.9"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.133"
sysinfo = "0.33.0"
tempfile = "3.14.0"
termimad = "0.31.1"
